version: '2'
services:

    api:
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        environment:
            SERVER_PORT: ${SERVER_PORT}
            MONGO_STRING2: ${MONGO_STRING2}
            MONGO_STRING1: ${MONGO_STRING1}
            JWT_SECRET: ${JWT_SECRET}
            
