version: '2'
services:
 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
    environment: [
        'http.host=0.0.0.0',
        'transport.host=127.0.0.1',
        'xpack.security.enabled=false',
        'http.cors.enabled=true',
        'http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/'
    ]
    ports: ['127.0.0.1:9200:9200']
