version: '2'
services:

    mongodb:
        image: mongo:latest
        volumes:
            - ./data/db:/data/db
        container_name: 'mongo'
        ports:
            - 27017:27017

        #to run as a replica set
        # entrypoint: ['/usr/bin/mongod', '--replSet', 'rs', '--smallfiles', '--httpinterface', '--rest']


    api:
        links:
            - mongodb:db
        depends_on:
            - mongodb
